view.yaml: Rename to Hafnium.yaml
As per jenkins-job-builder conventions, file name should match name of
element inside it, otherwise there's an error:

ValueError: Job name Hafnium does not match the file it is in: view

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>
Change-Id: I6ce9966c13753fc236853b687974877b03067fcd